#!/usr/bin/env python3
"""Emit milestone-data.js: for each tech, the strongest unit it unlocks.

Old World displays unit strength as iStrength / 10 (Swordsman iStrength 80 = "8").
Used by Plan & Optimize's "8-strength unit timing" milestone. Laws come from
tech-data.js (unlocks.laws), so only unit strength needs generating here.

Run:  python3 gen_milestone_data.py
"""
import re, json, os

XML = "/Users/dominik/Library/Application Support/Steam/steamapps/common/Old World/Reference/XML/Infos/unit.xml"


def display_name(ztype):
    return ztype.replace("UNIT_", "").replace("_", " ").title()


def main():
    src = open(XML).read()
    best = {}  # techId -> (strength, unitName)
    for e in re.findall(r"<Entry>(.*?)</Entry>", src, re.S):
        z = re.search(r"<zType>(UNIT_[A-Z0-9_]+)</zType>", e)
        tp = re.search(r"<TechPrereq>(TECH_[A-Z0-9_]+)</TechPrereq>", e)
        st = re.search(r"<iStrength>(\d+)</iStrength>", e)
        if not (z and tp and st):
            continue
        strength = int(st.group(1)) / 10.0
        tech = tp.group(1)
        if tech not in best or strength > best[tech][0]:
            best[tech] = (strength, display_name(z.group(1)))

    out = {t: {"str": (int(s) if s == int(s) else s), "unit": u} for t, (s, u) in best.items()}
    js = (
        "// GENERATED by gen_milestone_data.py — do not edit by hand.\n"
        "// Strongest unit each tech unlocks (displayed strength = iStrength/10).\n\n"
        f"export const unitStrengthByTech = {json.dumps(out, indent=0).replace(chr(10), ' ')};\n"
    )
    path = os.path.join(os.path.dirname(__file__), "milestone-data.js")
    open(path, "w").write(js)
    strong = sorted(((v["str"], t, v["unit"]) for t, v in out.items()), reverse=True)
    print(f"techs unlocking units: {len(out)} | with >=8 strength: {sum(1 for v in out.values() if v['str'] >= 8)}")
    for s, t, u in strong[:10]:
        print(f"  {s:>4}  {t.replace('TECH_',''):20} {u}")
    print("wrote", path)


if __name__ == "__main__":
    main()
