// GENERATED by gen_science_model.py — do not edit by hand.
// Per-tech science contributions: data-decomposed from owglick winning games
// where supported, else the game-XML science magnitude (anchored to data).
// games=98, since=2026-05-07

export const scienceTechs = ["TECH_DIVINATION", "TECH_SCHOLARSHIP", "TECH_MONASTICISM", "TECH_HYDRAULICS", "TECH_WINDLASS", "TECH_METAPHYSICS", "TECH_ARCHITECTURE"];

export const scienceWeights = {"TECH_DIVINATION": 3.41, "TECH_SCHOLARSHIP": 10.23, "TECH_MONASTICISM": 4.61, "TECH_HYDRAULICS": 6.82, "TECH_WINDLASS": 6.82, "TECH_METAPHYSICS": 4.09, "TECH_ARCHITECTURE": 5.12};

export const scienceProvenance = {"TECH_DIVINATION": "data", "TECH_SCHOLARSHIP": "mechanic", "TECH_MONASTICISM": "data", "TECH_HYDRAULICS": "mechanic", "TECH_WINDLASS": "mechanic", "TECH_METAPHYSICS": "mechanic", "TECH_ARCHITECTURE": "mechanic"};

export const avgHas = {"TECH_DIVINATION": [[5, 0.3061], [10, 0.8163], [15, 0.8469], [20, 0.8571], [25, 0.8763], [30, 0.9167], [35, 0.9239], [40, 0.9213], [45, 0.9765], [50, 0.9877], [55, 1.0], [60, 1.0]], "TECH_SCHOLARSHIP": [[5, 0.0], [10, 0.0], [15, 0.0], [20, 0.0], [25, 0.0], [30, 0.0], [35, 0.0], [40, 0.0], [45, 0.0], [50, 0.0], [55, 0.0], [60, 0.0]], "TECH_MONASTICISM": [[5, 0.0], [10, 0.0], [15, 0.0], [20, 0.0], [25, 0.0103], [30, 0.0208], [35, 0.0217], [40, 0.0225], [45, 0.0588], [50, 0.2099], [55, 0.2687], [60, 0.3333]], "TECH_HYDRAULICS": [[5, 0.0], [10, 0.0], [15, 0.0], [20, 0.0], [25, 0.0], [30, 0.0], [35, 0.0], [40, 0.0], [45, 0.0], [50, 0.0123], [55, 0.0149], [60, 0.0333]], "TECH_WINDLASS": [[5, 0.0], [10, 0.0], [15, 0.0], [20, 0.0], [25, 0.0], [30, 0.0], [35, 0.0], [40, 0.0], [45, 0.0], [50, 0.0], [55, 0.0], [60, 0.0]], "TECH_METAPHYSICS": [[5, 0.0102], [10, 0.0102], [15, 0.0102], [20, 0.0102], [25, 0.0206], [30, 0.0208], [35, 0.0217], [40, 0.0337], [45, 0.0235], [50, 0.037], [55, 0.0299], [60, 0.0667]], "TECH_ARCHITECTURE": [[5, 0.0], [10, 0.0], [15, 0.0], [20, 0.0], [25, 0.0], [30, 0.0], [35, 0.0326], [40, 0.0449], [45, 0.0588], [50, 0.0988], [55, 0.1194], [60, 0.1333]]};
